#!/bin/bash

have_command() {
    if command -v "$1" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

install_fastfetch() {
    if have_command fastfetch; then
        echo "fastfetch has installed"
        return 0
    fi

    case "$system_arch" in
        x86_64)
            file_arch="amd64"
            ;;
        aarch64|arm64)
            file_arch="aarch64"
            ;;
        *)
            echo "arch not support, fastfetch install aborted"
            return 1
            ;;
    esac

    url="https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-${file_arch}.deb"
    output_file="/tmp/fastfetch-linux-${file_arch}.deb"

    if ! curl -L -o "$output_file" "$url"; then
        echo "Download failed, fastfetch install aborted"
        return 1
    fi

    if ! sudo dpkg -i "$output_file"; then
        echo "Installation failed, fastfetch install aborted"
        return 1
    fi

    echo "fastfetch Installed successfully"
    return 0
}


if [[ "$system_type" == "Darwin" ]]; then
    brew bundle --file=~/.config/yadm/Brewfile --no-lock
fi

if [[ "$local_class" == "server" ]]; then
    sudo apt install -y zsh tmux vim tar bzip2 zip unzip htop lf ufw fail2ban acl rclone restic
    install_fastfetch
fi
