#!/bin/bash

have_command() {
    if command -v "$1" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

install_lf() {
    if have_command lf; then
        echo "lf has installed"
        return 0
    fi

    case "$system_arch" in
        i386|i686)
            file_arch="386"
            ;;
        x86_64)
            file_arch="amd64"
            ;;
        armv7*|armv6*|armv5*)
            file_arch="arm"
            ;;
        aarch64|arm64)
            file_arch="arm64"
            ;;
        *)
            echo "arch not support, lf install aborted"
            return 1
            ;;
    esac

    url="https://github.com/gokcehan/lf/releases/latest/download/lf-linux-${file_arch}.tar.gz"
    output_file="/tmp/lf-linux-${file_arch}.tar.gz"

    if ! curl -L -o "$output_file" "$url"; then
        echo "Download failed, lf install aborted"
        return 1
    fi

    if ! sudo tar -xzf "$output_file" -C /usr/local/bin; then
        echo "Extraction failed, lf install aborted"
        return 1
    fi

    echo "lf Installed successfully"
    return 0
}

install_fastfetch() {
    if have_command fastfetch; then
        echo "fastfetch has installed"
        return 0
    fi

    case "$system_arch" in
        x86_64)
            file_arch="amd64"
            ;;
        aarch64|arm64)
            file_arch="aarch64"
            ;;
        *)
            echo "arch not support, fastfetch install aborted"
            return 1
            ;;
    esac

    url="https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-${file_arch}.deb"
    output_file="/tmp/fastfetch-linux-${file_arch}.deb"

    if ! curl -L -o "$output_file" "$url"; then
        echo "Download failed, fastfetch install aborted"
        return 1
    fi

    if ! sudo dpkg -i "$output_file"; then
        echo "Installation failed, fastfetch install aborted"
        return 1
    fi

    echo "fastfetch Installed successfully"
    return 0
}


if [[ "$system_type" == "Darwin" ]]; then
    brew bundle --file=~/.config/yadm/Brewfile --no-lock
fi

if [[ "$local_class" == "server" ]]; then
    sudo apt install -y zsh tmux tar vim zip unzip htop
    install_lf
    install_fastfetch
fi
