export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="pi"

unsetopt autocd

# == omz plugins ==
plugins=(
    git
    docker
    docker-compose
    autojump
    zsh-syntax-highlighting
    zsh-autosuggestions
)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

source $ZSH/oh-my-zsh.sh

# == path ===
# user local
export PATH="$HOME/.local/bin:$PATH"
# rust
. "$HOME/.cargo/env"
# golang
export PATH="$HOME/go/bin:$PATH"
# node version manager
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# == enviroment variable ==
export EDITOR='vim'
export GPG_TTY=$(tty)
if command -v bat >/dev/null 2>&1; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi
# = fzf =
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'
export FZF_DEFAULT_OPTS="
--layout=reverse
--height 80%
--border
--preview 'bat {}'
--bind 'ctrl-/:change-preview-window(hidden|),ctrl-y:preview-half-page-up,ctrl-e:preview-half-page-down,ctrl-f:page-down,ctrl-b:page-up'
"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="$FZF_DEFAULT_OPTS"

# == alias ==
alias ea="exa -laHT -I .git --icons"
alias vim="nvim"
alias lg="lazygit"
alias fm="joshuto"
alias gnpm="$HOMEBREW_PREFIX/bin/pnpm"
alias fork="open -a Fork.app"
alias typora="open -a typora"
alias ws="webstorm"
eval "$(github-copilot-cli alias -- "$0")"

# == external script ==
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# == zsh completion ==
if command -v colima >/dev/null 2>&1; then
  source <(colima completion zsh)
fi
if command -v ng >/dev/null 2>&1; then
  source <(ng completion script)
fi
