# cat << EOF > /dev/null

# -- tmux sensible
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0
# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5
# Upgrade $TERM
set -g default-terminal "screen-256color"
# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs
# Focus events enabled for terminals that support them
set -g focus-events on
# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# -- general
setw -g xterm-keys on
set -sg repeat-time 300
set -g mouse on
set -sg exit-empty on

set -q -g status-utf8 on
setw -q -g utf8 on

set -g visual-activity off
setw -g monitor-activity off
setw -g monitor-bell off


# -- prefix
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# -- display
set -g base-index 1
setw -g pane-base-index 1

# window management
bind u split-window -vb -c "#{pane_current_path}"
bind e split-window -v -c "#{pane_current_path}"
bind n split-window -hb -c "#{pane_current_path}"
bind i split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

# window navigation
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 0

# pane navigation
bind -n M-n select-pane -L
bind -n M-e select-pane -D
bind -n M-u select-pane -U
bind -n M-i select-pane -R
# pane resizing
bind -n M-N resize-pane -L 3
bind -n M-E resize-pane -D 3
bind -n M-U resize-pane -U 3
bind -n M-I resize-pane -R 3

# reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display 'tmux config reloaded!'

# default statusbar colors
set -g status-bg black
set -g status-left "#[fg=magenta,bold]#S ❐ "
set -g status-right "#[fg=cyan]%a %m-%d %R"
setw -g window-status-format '#[fg=cyan]#I.#W'
setw -g window-status-current-format '#[fg=brightyellow,bold]#I.#W#F'
setw -g window-status-activity-style bg=black
setw -g window-status-bell-style bg=black

